y = zeros(8,13);
y = xlsread('D:\com.xlsx');
C = cool(7);
figure;
plot(y(:,1),y(:,4),'Color',[32/255 178/255 170/255],'linewidth',3,'LineStyle',"-.");
hold on;
plot(y(:,1),y(:,3),'Color',C(2,:),'linewidth',3,'LineStyle',"--");
hold on;
plot(y(:,1),y(:,2),'Color',C(3,:),'linewidth',3,'LineStyle',"-");
hold on;
plot(y(:,1),y(:,5),'Color',C(4,:),'linewidth',3,'LineStyle',":");
hold on;
plot(y(:,1),y(:,6),'Color',C(5,:),'linewidth',1.5,'LineStyle',"-.");
hold on;
plot(y(:,1),y(:,7),'Color',C(6,:),'linewidth',1.5,'LineStyle',"--");
hold on;
plot(y(:,1),y(:,8),'Color',C(7,:),'linewidth',1.5,'LineStyle',":");
hold off;
legend('SVND','SVM','LDA','QDA','KNN','NB','DT');
